# XC7A35TICSG324-1L
export XRAY_PART=xc7a35tcsg324-1
export XRAY_PINCFG=ARTY-A7-SWBUT
export XRAY_DIN_N_LARGE=0
export XRAY_DOUT_N_LARGE=3

# HCLK Tile
export XRAY_ROI_HCLK="CLK_HROW_TOP_R_X60Y130/CLK_HROW_CK_BUFHCLK_L0"

# PITCH
export XRAY_PITCH=2

source $XRAY_DIR/utils/environment.sh
